[package]
name = "glam-cpi-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-gen = { path = "../anchor-gen" }
anchor-idl = { path = "../anchor-idl" }
quote = "1"
clap = { version = "4.0", features = ["derive"] }
proc-macro2 = "1.0"
prettyplease = "0.2"
syn = "2"
serde_json = "1"
